---
title: "Network Analysis"
author: "Lachlan Baer"
date: "09/07/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Setup R

```{r}
# Load libraries
library(magrittr)
library(plyr)
library(tidyverse)
library(igraph)
library(tidygraph)
library(ggraph)
library(fgsea)
```

# Network Analysis
  
## Load data
  
```{r}
# Load significant pathways with ONLY leading edge genes determined from GSEA analysis
sigHallmark <-
  readRDS("2019_analysis_files/fgseaHallmark.rds") %>%
  split(f = .$pathway) %>% 
  lapply(extract2, "leadingEdge") %>% 
  lapply(unlist)
sigKEGG <- 
  readRDS("2019_analysis_files/fgseaKEGG.rds") %>%
  split(f = .$pathway) %>% 
  lapply(extract2, "leadingEdge") %>%
  lapply(unlist)
sigWiki <- 
  readRDS("2019_analysis_files/fgseaWiki.rds") %>%
  split(f = .$pathway) %>% 
  lapply(extract2, "leadingEdge") %>% 
  lapply(unlist)
```

## Hallmark

```{r}
# Create a node list
pathwaysHallmark <- names(sigHallmark) %>%
  as.data.frame() %>%
  set_colnames("label")
genesHallmark <- unique(unlist(sigHallmark)) %>% 
  as.data.frame() %>% 
  set_colnames("label")
nodesHallmark <- full_join(pathwaysHallmark, genesHallmark, by = "label") %>%
  rowid_to_column("id")
# Then create an edge list
edgesHallmark <- ldply(sigHallmark, data.frame) %>% 
  set_colnames(c("pathway", "gene")) %>%
  left_join(nodesHallmark, by = c("pathway" = "label")) %>%
  dplyr::rename(from = id) %>%
  left_join(nodesHallmark, by = c("gene" = "label")) %>%
  dplyr::rename(to = id) %>%
  dplyr::select(from, to)
```

```{r}
# Create tidygraph object
# tidyHallmark <- 
  tbl_graph(nodes = nodesHallmark, edges = edgesHallmark, directed = FALSE) %>%
  activate(nodes) %>%
  left_join(ens2Entrez, by = c("label" = "Entrez"))
  mutate(text = case_when(id < 14 ~ label)) %>%
  mutate(size = ifelse(id < 14, 2, 1)) %>%
  mutate(colour = ifelse(id < 14, rainbow(14)[id], NA)) %>%
  activate(edges) %>%
  mutate(colour = ifelse(from < 14, rainbow(14)[from], NA))
# Plot graph
ggraph(tidyHallmark, layout = "kk") +
  geom_edge_arc(aes(color = colour), alpha = 0.4, show.legend = FALSE, curvature = 0.5) +
  geom_node_point(aes(size = size, fill = colour), shape = 21, stroke = 0.5, 
                  colour = "black", show.legend = FALSE) +
  geom_node_label(aes(label = text), repel = TRUE, size = 2.5, alpha = 0.7) +
  theme_graph() +
  theme(legend.position = "none")
```

## KEGG

```{r}
# Create a node list
pathwaysKEGG <- names(sigKEGG) %>%
  as.data.frame() %>%
  set_colnames("label")
genesKEGG <- unique(unlist(sigKEGG)) %>% 
  as.data.frame() %>% 
  set_colnames("label")
nodesKEGG <- full_join(pathwaysKEGG, genesKEGG, by = "label") %>%
  rowid_to_column("id")
# Then create an edge list
edgesKEGG <- ldply(sigKEGG, data.frame) %>% 
  set_colnames(c("pathway", "gene")) %>%
  left_join(nodesKEGG, by = c("pathway" = "label")) %>%
  dplyr::rename(from = id) %>%
  left_join(nodesKEGG, by = c("gene" = "label")) %>%
  dplyr::rename(to = id) %>%
  dplyr::select(from, to)
```

```{r}
# Create tidygraph object
tidyKEGG <- tbl_graph(nodes = nodesKEGG, edges = edgesKEGG, directed = FALSE) %>%
  activate(nodes) %>%
  mutate(text = ifelse(id < 27, label, NA)) %>%
  mutate(size = ifelse(id < 27, 2, 1)) %>%
  mutate(colour = ifelse(id < 27, rainbow(27)[id], NA)) %>%
  activate(edges) %>%
  mutate(colour = ifelse(from < 27, rainbow(27)[from], NA))
# Plot graph
ggraph(tidyKEGG, layout = "kk") +
  geom_edge_arc(aes(color = colour), alpha = 0.4, show.legend = FALSE, curvature = 0.5) +
  geom_node_point(aes(size = size, fill = colour), shape = 21, stroke = 0.5, 
                  colour = "black", show.legend = FALSE) +
  # geom_node_text(aes(label = text), repel = TRUE, size = 2.5) +
  geom_node_label(aes(label = text), repel = TRUE, size = 2.5, alpha = 0.7) +
  theme_graph() +
  theme(legend.position = "none")
```

## WikiPathways

```{r}
# Create a node list
pathwaysWiki <- names(sigWiki) %>%
  as.data.frame() %>%
  set_colnames("label")
genesWiki <- unique(unlist(sigWiki)) %>% 
  as.data.frame() %>% 
  set_colnames("label")
nodesWiki <- full_join(pathwaysWiki, genesWiki, by = "label") %>%
  rowid_to_column("id")
# Then create an edge list
edgesWiki <- ldply(sigWiki, data.frame) %>% 
  set_colnames(c("pathway", "gene")) %>%
  left_join(nodesWiki, by = c("pathway" = "label")) %>%
  dplyr::rename(from = id) %>%
  left_join(nodesWiki, by = c("gene" = "label")) %>%
  dplyr::rename(to = id) %>%
  dplyr::select(from, to)
```

```{r}
# Create tidygraph object
tidyWiki <- tbl_graph(nodes = nodesWiki, edges = edgesWiki, directed = FALSE) %>%
  activate(nodes) %>%
  mutate(text = ifelse(id < 16, label, NA)) %>%
  mutate(size = ifelse(id < 16, 20, 1)) %>%
  mutate(colour = ifelse(id < 16, rainbow(16)[id], NA)) %>%
  activate(edges) %>%
  mutate(colour = ifelse(from < 16, rainbow(16)[from], NA))
# Plot graph
ggraph(tidyWiki, layout = "kk") +
  geom_edge_arc(aes(color = colour), alpha = 0.4, show.legend = FALSE, curvature = 0.5) +
  geom_node_point(aes(size = size, fill = colour), shape = 21, stroke = 0.5, 
                  colour = "black", show.legend = FALSE) +
  geom_node_text(aes(label = text), repel = TRUE, size = 2.5) +
  theme_graph()
```

## Comparison without tidygraph/ggraph

```{r echo=FALSE}
sigTest <-
  readRDS("2019_analysis_files/fgseaKEGG.rds") %>%
  split(f = .$pathway) %>% 
  lapply(extract2, "leadingEdge") %>% 
  lapply(unlist) %>%
  ldply(data.frame) %>%
  as_tbl_graph()

plot.igraph(sigTest, vertex.size = 2, vertex.label.cex = 0.5, 
            vertex.label = ifelse(V(sigTest)$name %in% names(sigKEGG), V(sigTest)$name, NA), 
            edge.curved = 0.5, layout = layout.kamada.kawai, directed = FALSE)

ggraph(tidyKEGG, layout = "kk") +
  geom_edge_arc(aes(color = colour), alpha = 0.4, show.legend = FALSE, curvature = 0.5) +
  geom_node_point(aes(size = size, fill = colour), shape = 21, stroke = 0.5, 
                  colour = "black", show.legend = FALSE) +
  geom_node_text(aes(label = text), repel = TRUE, size = 2.5) +
  theme_graph()
```

# Pathway crosstalk perturbation network (PXPN)

## Load pathways

```{r}
hallmark <- gmtPathways("../files/h.all.v6.2.entrez.gmt")
names(hallmark) <- names(hallmark) %>% str_remove_all("HALLMARK_")

kegg <- gmtPathways("../files/c2.cp.kegg.v6.2.entrez.gmt")
names(kegg) <- names(kegg) %>% str_remove_all("KEGG_")

wiki <- gmtPathways("../files/wikipathways-20190610-gmt-Homo_sapiens.gmt")
names(wiki) <- names(wiki) %>% str_remove_all("%.+")
```

## Step 1) Pathway perturbation between physiological states

```{r}
# This step is the pathways determined to be perturbed by a standard GSEA
# Load fgsea results
fgseaHallmark <- readRDS("2019_analysis_files/fgseaHallmark.rds")
# Extract pathways found to be perturbed
pertPathHallmark <- hallmark[fgseaHallmark$pathway]
```

## Step 2) Crosstalk between perturbed pathways

```{r}
for (i in pertPathHallmark) {
  for (j in pertPathHallmark) {
    if (intersect(i,j) != 0) {
      crosstalk = TRUE
      crosstalk(i,j) = intersect(i,j)
      crosstalkHallmark <- add(crosstalk(i,j))
    } else
      crosstalk == FALSE
  }
}

return(crosstalk_list)
crosstalk_list 
```

## Step 3) Crosstalk perturbation between physological states

```{r}

```

## Step 4) Network integration

```{r}

```

